//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmfestival
{
    using System;
    using System.Collections.Generic;
    
    public partial class actor_film_director
    {
        public int id_film { get; set; }
        public int id_director { get; set; }
        public int id_actor { get; set; }
    
        public virtual actor actor { get; set; }
        public virtual director director { get; set; }
        public virtual film film { get; set; }
    }
}
