//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmfestival
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FILM_FESTIVALEntities : DbContext
    {
        public FILM_FESTIVALEntities()
            : base("name=FILM_FESTIVALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actor> actors { get; set; }
        public virtual DbSet<director> directors { get; set; }
        public virtual DbSet<film> films { get; set; }
        public virtual DbSet<actor_film_director> actor_film_director { get; set; }
        public virtual DbSet<film_nomination> film_nomination { get; set; }
        public virtual DbSet<userinformation> userinformations { get; set; }
    }
}
